name: install-tools
description: "Install tools"
inputs:
  github-token:
    description: Github token
    required: true
  cachix-token:
    description: Cachix token
    required: true
  tailscale_client:
    description: Tailscale oauth client id
    required: true
  tailscale_secret:
    description: Tailscale oauth secret
    required: true
runs:
  using: composite
  steps:
      - name: Tailscale
        uses: tailscale/github-action@84a3f23bb4d843bcf4da6cf824ec1be473daf4de # v3.2.3
        with:
          oauth-client-id: ${{ inputs.tailscale_client }}
          oauth-secret: ${{ inputs.tailscale_secret }}
          tags: tag:ci
          args: --ssh

      - uses: chainguard-dev/actions/setup-gitsign@4f7ad4fd63a4e1c8c11fdb16d543a3eb651036ca # v1.4.2

      - name: Configure nix, Determinate Systems
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v31.4.1
        with:
          github-token: ${{ inputs.github-token }}
          extra-conf:  |-
            substituters = https://cache.nixos.org?priority=15 https://a1994sc.cachix.org?priority=15 https://danu-01.barb-neon.ts.net https://danu-02.barb-neon.ts.net
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= a1994sc.cachix.org-1:xZdr1tcv+XGctmkGsYw3nXjO1LOpluCv4RDWTqJRczI= danu-01.barb-neon.ts.net:wjXASA3VF+ryB3brRo8vPMuYwVGrjsIa+a3pe8zV86o= danu-02.barb-neon.ts.net:SqCBNF/wWsRQU5QGLhoV58KEcEZKRW39LQxxXYWLH/0=

      - name: Setup SSH Keys
        shell: bash
        continue-on-error: true
        run: |-
          mkdir -p ~/.ssh

          cat << 'EOF' >> ~/.ssh/known_hosts
          danu-01.barb-neon.ts.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKgtCFdGSN+0iuaD6WpspN7tB7bZk0nuUqeY4Mq7k5Df
          danu-02.barb-neon.ts.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGGZ4rS2mbNzQYWtYxZIpDv+xLkI4UHLov8ICjH3FkkG
          EOF

          ssh custodian@danu-01.barb-neon.ts.net echo "SSH connection successful"

      - name: Setup Nix config
        shell: bash
        continue-on-error: true
        run: |-
          mkdir -p ~/.local/share/nix ~/.config/nix/nix

          cat << 'EOF' >> ~/.config/nix/nix.conf
          substituters = https://cache.nixos.org/?priority=25 https://a1994sc.cachix.org?priority=20 https://danu-01.barb-neon.ts.net https://danu-02.barb-neon.ts.net
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= a1994sc.cachix.org-1:xZdr1tcv+XGctmkGsYw3nXjO1LOpluCv4RDWTqJRczI= danu-01.barb-neon.ts.net:wjXASA3VF+ryB3brRo8vPMuYwVGrjsIa+a3pe8zV86o= danu-02.barb-neon.ts.net:SqCBNF/wWsRQU5QGLhoV58KEcEZKRW39LQxxXYWLH/0=
          EOF

          cat << 'EOF' >> ~/.local/share/nix/trusted-settings.json
          {
            "extra-substituters": {
              "danu-01.barb-neon.ts.net": true,
              "https://danu-01.barb-neon.ts.net": true,
              "danu-02.barb-neon.ts.net": true,
              "https://danu-02.barb-neon.ts.net": true,
              "a1994sc.cachix.org": true,
              "https://a1994sc.cachix.org": true
            },
            "extra-trusted-public-keys": {
              "danu-01.barb-neon.ts.net:wjXASA3VF+ryB3brRo8vPMuYwVGrjsIa+a3pe8zV86o=": true,
              "danu-02.barb-neon.ts.net:SqCBNF/wWsRQU5QGLhoV58KEcEZKRW39LQxxXYWLH/0=": true,
              "a1994sc.cachix.org-1:xZdr1tcv+XGctmkGsYw3nXjO1LOpluCv4RDWTqJRczI=": true
            },
            "extra-trusted-substituters": {
              "https://danu-01.barb-neon.ts.net": true,
              "https://danu-02.barb-neon.ts.net": true,
              "https://a1994sc.cachix.org": true
            },
            "trusted-public-keys": {
              "danu-01.barb-neon.ts.net:wjXASA3VF+ryB3brRo8vPMuYwVGrjsIa+a3pe8zV86o=": true,
              "danu-02.barb-neon.ts.net:SqCBNF/wWsRQU5QGLhoV58KEcEZKRW39LQxxXYWLH/0=": true,
              "a1994sc.cachix.org-1:xZdr1tcv+XGctmkGsYw3nXjO1LOpluCv4RDWTqJRczI=": true,
              "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=": true
            }
          }
          EOF

      - name: Add cachix actions
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: '${{ inputs.cachix-token }}'
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$|.patch$)
