name: "builds"
on:
  workflow_run:
    workflows:
      - "Update lock"
      - "auto-magic update packages"
    types:
      - completed
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - id: set-matrix
        env:
          PKG_DIR: pkgs/core
        run: |-
          echo "matrix=$(nix flake show --json --all-systems 2>/dev/null | yq -M -pj -oj -I0 '. = ([.packages.x86_64-linux | keys | .[] | select(. != "go-1*")]) | .[] |= {"pkg": .} | {"include": .}')" >> $GITHUB_OUTPUT

  compilers:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        comp:
          - "clang"
          - "go-1-23"
          - "go-1-24"
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        exclude:
          - os: ubuntu-24.04-arm
            comp: "clang"
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@84a3f23bb4d843bcf4da6cf824ec1be473daf4de # v3.2.3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          args: --ssh

      - name: Setup SSH Keys
        continue-on-error: true
        run: |-
          mkdir -p ~/.ssh

          cat << 'EOF' >> ~/.ssh/known_hosts
          danu-01.barb-neon.ts.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKgtCFdGSN+0iuaD6WpspN7tB7bZk0nuUqeY4Mq7k5Df
          danu-02.barb-neon.ts.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGGZ4rS2mbNzQYWtYxZIpDv+xLkI4UHLov8ICjH3FkkG
          EOF

          ssh custodian@danu-01.barb-neon.ts.net echo "SSH connection successful"

      - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$)

      - name: Build updated package
        run: |-
          nix build .#${{ matrix.comp }}

      - name: Push build to caches
        continue-on-error: true
        run: |-
          nix copy --to ssh://custodian@danu-01.barb-neon.ts.net ".#${{ matrix.comp }}"
          nix copy --to ssh://custodian@danu-02.barb-neon.ts.net ".#${{ matrix.comp }}"

  release:
    needs:
      - compilers
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@84a3f23bb4d843bcf4da6cf824ec1be473daf4de # v3.2.3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          args: --ssh

      - name: Setup SSH Keys
        continue-on-error: true
        run: |-
          mkdir -p ~/.ssh

          cat << 'EOF' >> ~/.ssh/known_hosts
          danu-01.barb-neon.ts.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKgtCFdGSN+0iuaD6WpspN7tB7bZk0nuUqeY4Mq7k5Df
          danu-02.barb-neon.ts.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGGZ4rS2mbNzQYWtYxZIpDv+xLkI4UHLov8ICjH3FkkG
          EOF

          ssh custodian@danu-01.barb-neon.ts.net echo "SSH connection successful"

      - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$)

      - name: Build updated package
        run: |-
          nix build .#${{ matrix.pkg }}

      - name: Push build to caches
        continue-on-error: true
        run: |-
          nix copy --to ssh://custodian@danu-01.barb-neon.ts.net ".#${{ matrix.pkg }}"
          nix copy --to ssh://custodian@danu-02.barb-neon.ts.net ".#${{ matrix.pkg }}"
