name: "builds"
on:
  workflow_run:
    workflows:
      - "Update lock"
      - "auto-magic update packages"
    types:
      - completed
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: cachix/install-nix-action@fc6e360bedc9ee72d75e701397f0bb30dce77568 # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - id: set-matrix
        env:
          PKG_DIR: pkgs/core
        run: |-
          echo "matrix=$(nix flake show --json --all-systems 2>/dev/null | yq -M -pj -oj -I0 '. = ([.packages.x86_64-linux | keys | .[] | select(. != "go-1*")]) | .[] |= {"pkg": .} | {"include": .}')" >> $GITHUB_OUTPUT

  compilers:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        comp:
          - "go-1-23"
          - "go-1-24"
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install Nix environment
        uses: ./.github/actions/install-tools
        timeout-minutes: 10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          tailscale_client: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          tailscale_secret: ${{ secrets.TS_OAUTH_SECRET }}

      - name: Build updated package
        run: |-
          nix build .#${{ matrix.comp }}

      - name: Push build to caches
        continue-on-error: true
        run: |-
          nix copy --to ssh://custodian@danu-01.barb-neon.ts.net ".#${{ matrix.comp }}"
          nix copy --to ssh://custodian@danu-02.barb-neon.ts.net ".#${{ matrix.comp }}"

  release:
    needs:
      - compilers
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
      max-parallel: 3
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install Nix environment
        uses: ./.github/actions/install-tools
        timeout-minutes: 10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          tailscale_client: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          tailscale_secret: ${{ secrets.TS_OAUTH_SECRET }}

      - name: Build updated package
        run: |-
          nix build .#${{ matrix.pkg }}

      - name: Push build to caches
        continue-on-error: true
        run: |-
          nix copy --to ssh://custodian@danu-01.barb-neon.ts.net ".#${{ matrix.pkg }}"
          nix copy --to ssh://custodian@danu-02.barb-neon.ts.net ".#${{ matrix.pkg }}"
