name: "builds"
on:
  workflow_run:
    workflows:
      - "Update lock"
      - "auto-magic update packages"
    types:
      - completed
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - id: set-matrix
        env:
          PKG_DIR: pkgs/core
        run: |-
          echo "matrix=$(nix flake show --json --all-systems 2>/dev/null | yq -M -pj -oj -I0 '. = ([.packages.x86_64-linux | keys | .[] | select(. != "go-1*")]) | .[] |= {"pkg": .} | {"include": .}')" >> $GITHUB_OUTPUT

  compilers:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        comp:
          - "go-1-23"
          - "go-1-24"
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: chainguard-dev/actions/setup-gitsign@be7b31a01af8ce7228fe901326f1d223fb788e14 # v1.4.12

      - name: Configure nix, Determinate Systems
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v31.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add cachix actions
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$|.patch$)

      - name: Build updated package
        run: |-
          nix build .#${{ matrix.comp }}

  release:
    needs:
      - compilers
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
      max-parallel: 3
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: chainguard-dev/actions/setup-gitsign@be7b31a01af8ce7228fe901326f1d223fb788e14 # v1.4.12

      - name: Configure nix, Determinate Systems
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v31.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add cachix actions
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$|.patch$)

      - name: Build updated package
        run: |-
          nix build .#${{ matrix.pkg }}
