name: "auto-magic update packages, legacy"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - id: set-matrix
        env:
          PKG_DIR: pkgs/core
        run: |-
          echo "matrix=$(nix flake show --legacy --json 2>/dev/null | yq -M -pj -oj -I=0 '. = ([.legacyPackages.x86_64-linux | keys | .[] | select(test("[^0-9]+$"))]) | .[] |= {"pkg": .} | {"include": .}')" >> $GITHUB_OUTPUT

  packages:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
      max-parallel: 3
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: chainguard-dev/actions/setup-gitsign@cd899cc96227b82170571cad1c3d6378d8cba678 # v1.4.15

      - name: Configure nix, Determinate Systems
        uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v31.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add cachix actions
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$|.patch$)

      - name: Get the url for package ${{ matrix.pkg }}
        id: homepage
        run: |-
          echo "URL=$(nix eval --raw .#legacyPackages.x86_64-linux.${{ matrix.pkg }}.meta.homepage --accept-flake-config)" >> "$GITHUB_OUTPUT"

      - name: Get latest version
        id: latest-version
        run: |
          pip install --constraint=.github/requirements.txt lastversion
          echo "version=$(python -m lastversion ${{ steps.homepage.outputs.URL }})" >> "$GITHUB_OUTPUT"

      - name: Build package with latest version
        if: ${{ steps.latest-version.outputs.version != '' }}
        run: |-
          nix run nixpkgs#nix-update -- --flake legacyPackages.x86_64-linux.${{ matrix.pkg }} --build --version ${{ steps.latest-version.outputs.version }}

      - name: Fetch changes
        run: |-
          git pull

      - name: Commit & Push changes
        id: commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          new_branch: 'update/${{ matrix.pkg }}-${{ steps.latest-version.outputs.version }}'
          message: "chore(pkg): update package ${{ matrix.pkg }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_author: github_actions

      - name: Create pull request
        if: ${{ steps.commit.outputs.committed == 'true' }}
        run: gh pr create -B 'main' -H 'update/${{ matrix.pkg }}-${{ steps.latest-version.outputs.version }}' --title 'Update ${{ matrix.pkg }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request, merge
        if: ${{ steps.commit.outputs.committed == 'true' }}
        id: merge
        continue-on-error: true
        run: gh pr merge --auto --delete-branch --merge 'update/${{ matrix.pkg }}-${{ steps.latest-version.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase on main
        if: ${{ steps.merge.outcome == 'failure' }}
        run: |-
          git rebase 'main'

      - name: Merge pull request, rebase
        if: ${{ steps.commit.outputs.committed == 'true' && steps.merge.outcome == 'failure' }}
        continue-on-error: true
        run: gh pr merge --auto --delete-branch --rebase 'update/${{ matrix.pkg }}-${{ steps.latest-version.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
