name: "auto-magic update packages"
on:
  workflow_dispatch:
  schedule:
    - cron: '15 */6 * * *'
jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  #     - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31.3.0
  #       with:
  #         nix_path: nixpkgs=channel:nixos-unstable
  #         github_access_token: ${{ secrets.GITHUB_TOKEN }}
  #     - id: set-matrix
  #       env:
  #         PKG_DIR: pkgs/core
  #       run: |-
  #         echo "matrix=$(nix flake show --json --all-systems 2>/dev/null | yq -M -pj -oj -I=0 '. = ([.packages.x86_64-linux | keys | .[] | select(test("[^0-9]+$"))]) | .[] |= {"pkg": .} | {"include": .}')" >> $GITHUB_OUTPUT

  go-lang:
    # needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "23"
          - "24"
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: chainguard-dev/actions/setup-gitsign@d9b7e22c19086f609cfeaea6d3b3e34f7ecc7266 # v1.0.6

      - name: Configure nix
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31.3.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add cachix actions
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$)

      - name: Get latest version
        id: latest-version
        run: |
          pip install --constraint=.github/constraints.txt lastversion
          echo "latest_version=$(python -m lastversion --only '~1.${{ matrix.version }}' https://github.com/golang/go)" >> "$GITHUB_OUTPUT"

      - name: Get latest version of 1.${{ matrix.version }}
        run: |-
          nix develop .#ci --command bash -c "nix-update --flake go-1-${{ matrix.version }} --build --version ${{ steps.latest-version.outputs.latest_version }}"

      - name: Commit & Push changes
        id: commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          new_branch: 'update/go-lang-1-${{ matrix.version }}.x'
          message: "chore(pkg): update package go-1-${{ matrix.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        if: ${{ steps.commit.outputs.committed == 'true' }}
        run: gh pr create -B 'main' -H 'update/go-lang-1-${{ matrix.version }}.x' --title 'Update golang 1-${{ matrix.version }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  packages:
    needs:
      - go-lang
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
      matrix:
        pkgs:
          - zarf
          - talosctl
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: chainguard-dev/actions/setup-gitsign@d9b7e22c19086f609cfeaea6d3b3e34f7ecc7266 # v1.0.6

      - name: Configure nix
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31.3.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add cachix actions
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$)

      - name: Get the url for package ${{ matrix.pkgs }}
        id: homepage
        run: |-
          echo "URL=$(nix eval --raw .#packages.x86_64-linux.${{ matrix.pkgs }}.meta.homepage)" >> "$GITHUB_OUTPUT"

      - name: Get latest version
        id: latest-version
        run: |
          pip install --constraint=.github/constraints.txt lastversion
          export VERSION=$(python -m lastversion ${{ steps.homepage.outputs.URL }})
          echo $VERSION
          echo "latest_version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build package with latest version
        run: |-
          nix develop .#ci --command bash -c "nix-update --flake ${{ matrix.pkgs }} --build --version ${{ steps.latest-version.outputs.VERSION }}"

      - name: Commit & Push changes
        id: commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          new_branch: 'update/${{ matrix.pkgs }}-${{ steps.latest-version.outputs.VERSION }}'
          message: "chore(pkg): update package ${{ matrix.pkgs }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        if: ${{ steps.commit.outputs.committed == 'true' }}
        run: gh pr create -B 'main' -H 'update/${{ matrix.pkgs }}-${{ steps.latest-version.outputs.VERSION }}' --title 'Update ${{ matrix.pkgs }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
