name: "auto-magic update packages, legacy"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31.4.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - id: set-matrix
        env:
          PKG_DIR: pkgs/core
        run: |-
          echo "matrix=$(nix flake show --legacy --json 2>/dev/null | yq -M -pj -oj -I=0 '. = ([.legacyPackages.x86_64-linux | keys | .[] | select(test("[^0-9]+$"))]) | .[] |= {"pkg": .} | {"include": .}')" >> $GITHUB_OUTPUT

  packages:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
      max-parallel: 3
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@6986d2c82a91fbac2949fe01f5bab95cf21b5102 # v3.2.2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          args: --ssh

      - name: Setup SSH Keys
        continue-on-error: true
        run: |-
          mkdir -p ~/.ssh

          cat << 'EOF' >> ~/.ssh/known_hosts
          danu-01.barb-neon.ts.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKgtCFdGSN+0iuaD6WpspN7tB7bZk0nuUqeY4Mq7k5Df
          danu-02.barb-neon.ts.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGGZ4rS2mbNzQYWtYxZIpDv+xLkI4UHLov8ICjH3FkkG
          EOF

          ssh custodian@danu-01.barb-neon.ts.net echo "SSH connection successful"

      - name: Setup Nix config
        continue-on-error: true
        run: |-
          mkdir -p ~/.local/share/nix ~/.config/nix/nix

          cat << 'EOF' >> ~/.config/nix/nix.conf
          substituters = https://danu-01.barb-neon.ts.net?priority=1 https://danu-02.barb-neon.ts.net?priority=2 https://cache.nixos.org/ https://a1994sc.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= a1994sc.cachix.org-1:xZdr1tcv+XGctmkGsYw3nXjO1LOpluCv4RDWTqJRczI= danu-01.barb-neon.ts.net:YsJLlRCoNlqCI0U3FZSOXBkjoxBSbn9e2/JKU5U+sG4= danu-02.barb-neon.ts.net:72+XyWbHlihra4BU5UKQmrV+Z8OBA+9BnD2Gq03GyVY=
          EOF

          cat << 'EOF' >> ~/.local/share/nix/trusted-settings.json
          {
            "extra-substituters": {
              "danu-01.barb-neon.ts.net": true,
              "https://danu-01.barb-neon.ts.net": true,
              "danu-02.barb-neon.ts.net": true,
              "https://danu-02.barb-neon.ts.net": true,
              "a1994sc.cachix.org": true,
              "https://a1994sc.cachix.org": true
            },
            "extra-trusted-public-keys": {
              "danu-01.barb-neon.ts.net:YsJLlRCoNlqCI0U3FZSOXBkjoxBSbn9e2/JKU5U+sG4=": true,
              "danu-02.barb-neon.ts.net:72+XyWbHlihra4BU5UKQmrV+Z8OBA+9BnD2Gq03GyVY=": true,
              "a1994sc.cachix.org-1:xZdr1tcv+XGctmkGsYw3nXjO1LOpluCv4RDWTqJRczI=": true
            },
            "extra-trusted-substituters": {
              "https://danu-01.barb-neon.ts.net": true,
              "https://danu-02.barb-neon.ts.net": true,
              "https://a1994sc.cachix.org": true
            },
            "trusted-public-keys": {
              "danu-01.barb-neon.ts.net:YsJLlRCoNlqCI0U3FZSOXBkjoxBSbn9e2/JKU5U+sG4=": true,
              "danu-02.barb-neon.ts.net:72+XyWbHlihra4BU5UKQmrV+Z8OBA+9BnD2Gq03GyVY=": true,
              "a1994sc.cachix.org-1:xZdr1tcv+XGctmkGsYw3nXjO1LOpluCv4RDWTqJRczI=": true,
              "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=": true
            }
          }
          EOF

      - uses: chainguard-dev/actions/setup-gitsign@4f7ad4fd63a4e1c8c11fdb16d543a3eb651036ca # v1.4.2

      - name: Configure nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31.4.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |-
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = ssh://custodian@danu-01.barb-neon.ts.net?priority=1 ssh://custodian@danu-02.barb-neon.ts.net?priority=2 https://cache.nixos.org/

      - name: Add cachix actions
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: a1994sc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: (-source$|-go-modules$|.tar.gz$|-dist$|.patch$)

      - name: Get the url for package ${{ matrix.pkg }}
        id: homepage
        run: |-
          echo "URL=$(nix eval --raw .#legacyPackages.x86_64-linux.${{ matrix.pkg }}.meta.homepage --accept-flake-config)" >> "$GITHUB_OUTPUT"

      - name: Get latest version
        id: latest-version
        run: |
          pip install --constraint=.github/constraints.txt lastversion
          echo "version=$(python -m lastversion ${{ steps.homepage.outputs.URL }})" >> "$GITHUB_OUTPUT"

      - name: Build package with latest version
        if: ${{ steps.latest-version.outputs.version != '' }}
        run: |-
          nix run nixpkgs#nix-update -- --flake legacyPackages.x86_64-linux.${{ matrix.pkg }} --build --version ${{ steps.latest-version.outputs.version }}

      - name: Push build to caches
        continue-on-error: true
        run: |-
          nix copy --to ssh://custodian@danu-01.barb-neon.ts.net ".#legacyPackages.x86_64-linux.${{ matrix.pkg }}"
          nix copy --to ssh://custodian@danu-02.barb-neon.ts.net ".#legacyPackages.x86_64-linux.${{ matrix.pkg }}"

      - name: Fetch changes
        run: |-
          git pull

      - name: Commit & Push changes
        id: commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          new_branch: 'update/${{ matrix.pkg }}-${{ steps.latest-version.outputs.version }}'
          message: "chore(pkg): update package ${{ matrix.pkg }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_author: github_actions

      - name: Create pull request
        if: ${{ steps.commit.outputs.committed == 'true' }}
        run: gh pr create -B 'main' -H 'update/${{ matrix.pkg }}-${{ steps.latest-version.outputs.version }}' --title 'Update ${{ matrix.pkg }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request, merge
        if: ${{ steps.commit.outputs.committed == 'true' }}
        id: merge
        continue-on-error: true
        run: gh pr merge --auto --delete-branch --merge 'update/${{ matrix.pkg }}-${{ steps.latest-version.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase on main
        if: ${{ steps.merge.outcome == 'failure' }}
        run: |-
          git rebase 'main'

      - name: Merge pull request, rebase
        if: ${{ steps.commit.outputs.committed == 'true' && steps.merge.outcome == 'failure' }}
        continue-on-error: true
        run: gh pr merge --auto --delete-branch --rebase 'update/${{ matrix.pkg }}-${{ steps.latest-version.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
